

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.10.100"
  config.hostsupdater.aliases = ["development.local"]

  config.vm.provision "shell", inline: "cp -rf /vagrant/site /home/ubuntu/site"
  config.vm.provision "shell", inline: "sudo chmod -R 400 /home/ubuntu/site"
  config.vm.provision "shell", inline: "echo 'export LC_ALL=C' >> /home/ubuntu/.bashrc"

end
